### ISSUE TITLE
CLI command for displaying settings. 

### ISSUE THREAD

**Issue by doctrino** [cognitedata/cognite-gql-pygen#23]
🤔  Not a big fan of unsolicited output. How about a CLI command that echoes all loaded settings (and hides `client_secret`)? https://github.com/cognitedata/cognite-gql-pygen/pull/20/commits/e987080b1a07021c8ebef7a0cb85c6d634c647fd

_Originally posted by @frnhr in https://github.com/cognitedata/cognite-gql-pygen/pull/20#discussion_r1178108350_

**Comment by frnhr** [comment]
@doctrino this is already implemented in PR #20, this commit: https://github.com/cognitedata/cognite-gql-pygen/pull/20/commits/e987080b1a07021c8ebef7a0cb85c6d634c647fd

Unless we want something more sophisticated, of course.
