### ISSUE TITLE
Instance attributes are changed to dicts on write

### ISSUE THREAD

**Issue by sindreto** [cognitedata/cognite-gql-pygen#29]
**System information (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.10.0
 - gql-pygen Version: 0.4.0

**Describe the bug**
Instance attributes are changed to dicts on write.

**To Reproduce**
Consider the dummy FDM model
```
type Foo {
    name: String
}

type Bar {
    name: String
    foo: Foo
}

type Baz {
    bar: Bar
}
```
When using the autogenerated SDK, the following code fails with a `ValueError: No DomainModelAPI registered for <class 'dict'>` on the last line.
```
my_foo = Foo(
    name="My Foo",
)
my_bar = Bar(
    name="My Bar",
    foo=my_foo
)
my_baz = Baz(
    bar=my_bar
)
dm_client.foo.apply([my_foo])
dm_client.bar.apply([my_bar])
dm_client.baz.apply([my_baz])
```

The reason is that `my_bar.foo` becmes a dictionary when it is written by `dm_client`. Unit test demonstrating the issue: 
```
    def test_create_instance(self):
        my_foo = Foo(
            name="My Foo",
        )
        my_bar = Bar(
            name="My Bar",
            foo=my_foo
        )
        my_baz = Baz(
            bar=my_bar
        )
        self.dm_client.foo.apply([my_foo])
        self.dm_client.bar.apply([my_bar])
        # my_bar.foo = my_foo  # Test passes with this line
        self.assertIsInstance(my_bar.foo, Foo)  # This assertion fails
        self.dm_client.baz.apply([my_baz])
```

**Expected behavior**
The example code should run without issues, creating the instances in CDF.

**Comment by doctrino** [comment]
I am unable to recreate this bug. I also cannot find a place in the code where the input argument to `.apply` is mutated. Can you test in on `v0.4.4`?

**Comment by doctrino** [comment]
Confirm that the bug cannot be reproduced, so will close this issue now.
